### ISSUE TITLE
博主macos下面统译出错

### ISSUE THREAD

**Issue by hggq** [cpuimage/MTCNN#1]
404 行// float M_PI = 3.1415926535897932384626433832795f;
系统已经自定义了

87行，定义这个好像出错了
	char drive[_MAX_DRIVE];
	char dir[_MAX_DIR];
	char fname[_MAX_FNAME];
	char ext[_MAX_EXT];

下面是编译几个错误

/Users/hzq/demo/mtcnn/src/timing.h:31:5: error: non-void function 'nanotimer'
      should return a value [-Wreturn-type]
    return;
    ^
/Users/hzq/demo/mtcnn/src/main.cpp:87:13: error: use of undeclared identifier
      '_MAX_DRIVE'
        char drive[_MAX_DRIVE];
                   ^
/Users/hzq/demo/mtcnn/src/main.cpp:88:11: error: use of undeclared identifier
      '_MAX_DIR'
        char dir[_MAX_DIR];
                 ^
/Users/hzq/demo/mtcnn/src/main.cpp:89:13: error: use of undeclared identifier
      '_MAX_FNAME'
        char fname[_MAX_FNAME];
                   ^
/Users/hzq/demo/mtcnn/src/main.cpp:90:11: error: use of undeclared identifier
      '_MAX_EXT'
        char ext[_MAX_EXT];

**Comment by cpuimage** [comment]
已经修正了.
