### ISSUE TITLE
可以支持gpu吗

### ISSUE THREAD

**Issue by heyanglearning** [cpuimage/MTCNN#10]
请问程序可以支持gpu吗，项目原来是使用python+mxnet来做的，现在想提升效率，使用C++提升效率。

**Comment by cpuimage** [comment]
@heyanglearning 可以支持gpu是什么说法?推理的时候采用gpu?

**Comment by heyanglearning** [comment]
是的，使用gpu来做。

**Comment by cpuimage** [comment]
@heyanglearning 直接python不就可以了,仅仅推理的话.没必要改写成c++

**Comment by heyanglearning** [comment]
嗯好的，感谢您！
