### ISSUE TITLE
/MTCNN/src/main.cpp:56:20: error: ‘browse’ was not declared in this scope

### ISSUE THREAD

**Issue by chenyuqing** [cpuimage/MTCNN#13]
/home/tim/workspaces/AI_TEST_One_week/MTCNN/src/main.cpp:56:20: error: ‘browse’ was not declared in this scope
     browse(saveFile);
                    ^
CMakeFiles/mtcnn.dir/build.make:62: recipe for target 'CMakeFiles/mtcnn.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/mtcnn.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/mtcnn.dir/all' failed
make[1]: *** [CMakeFiles/mtcnn.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chenyuqing** [comment]
有人知道这是什么问题吗？

**Comment by cpuimage** [comment]
@chenyuqing 这个函数是用来查看图片结果的,不影响使用,可以注释掉.
