### ISSUE TITLE
在ARM v8下编译失败（raspberry pi 3b）

### ISSUE THREAD

**Issue by muzi2045** [cpuimage/MTCNN#2]
在支持neon的arm64系统下编译，layer.cpp处报错
“Pooling_arm_layer_creator” was not declared in this scope...
{"Pooling" , Pooling_arm_layer_creator},
在x86平台程序编译工作正常，在arm64下貌似找不到相应的层定义文件

**Comment by cpuimage** [comment]
函数名弄错了，已经修复。
