### ISSUE TITLE
在ARM64下编译成功，但是测试结果完全错误

### ISSUE THREAD

**Issue by muzi2045** [cpuimage/MTCNN#3]
编译过程正常，但是测试结果和x86上有较大偏差，x86上测试结果正常，但是到ARM端编译出来的测试结果完全错位，而且检测人脸数量也不对。

**Comment by cpuimage** [comment]
@muzi2045 这个我没有验证过，排查一下是不是ncnn的问题？

**Comment by muzi2045** [comment]
初步怀疑是ncnn的Mat数据格式发生了变化，后期需要看ARM_NEON下的代码进一步排查。
另外，该工程基于的ncnn版本号是多少？ @cpuimage

**Comment by cpuimage** [comment]
@muzi2045 排查下是不是传错图像格式了，确定传的数据是RGB不是YUV，BGR之类的？
具体见main.cpp中的ncnn::Mat::PIXEL_RGB。
ncnn::Mat ncnn_img = ncnn::Mat::from_pixels(inputImage, ncnn::Mat::PIXEL_RGB, Width, Height);

**Comment by muzi2045** [comment]
我测试的是.jpg图像文件，传入的图像格式没有问题，在x86下测试正常的话，问题应该不在main.cpp里面。

**Comment by cpuimage** [comment]
@muzi2045 对arm的函数进行注释处理，排查下是哪个操作不对。

**Comment by licaibiao** [comment]
遇到了相同的问题，请问这个问题有定位到问题原因么？
