### ISSUE TITLE
关于model文件bin和param

### ISSUE THREAD

**Issue by huangshaoguang** [cpuimage/MTCNN#4]
你的模型文件bin和param能不能由python生成的index、meta和data等文件转化来？如果可以，那过程又是怎么样？能说一下吗？谢谢！

**Comment by cpuimage** [comment]
@huangshaoguang 参见https://github.com/Tencent/ncnn/tree/master/tools
训练模型后通过工具转存权重出来。

**Comment by huangshaoguang** [comment]
谢谢你！
