### ISSUE TITLE
Compiling help.

### ISSUE THREAD

**Issue by MyraBaba** [cpuimage/MTCNN#5]
I compiled ncnn , how can I compile ?

it gave:

`/Users/alpullu/Projects/ncnn/build/MTCNN/src/mtcnn.cpp:196:24: error: use of undeclared identifier 'ceil'
`

thx

**Comment by MyraBaba** [comment]
I found solution to add the 👍 
#include <math.h> in mtnc.cpp

now its compiled.

is this the fastest possible way to detect faces in arm devices ie : raspi3 ?

**Comment by cpuimage** [comment]
@MyraBaba u need do more work(maybe update the new ncnn library) to make it fast in raspi3.

**Comment by MyraBaba** [comment]
Did you try on raspberry pi 3B+ ? 
I have : 
jetsonTx2
nanopct4 
Hikey970

Is it possible to have a realtime detection in 720p ?

**Comment by cpuimage** [comment]
@MyraBaba of course，use SIMD(single instruction multiple data) or GPU to make it real-time.
