### ISSUE TITLE
simple cam example

### ISSUE THREAD

**Issue by MyraBaba** [cpuimage/MTCNN#6]
Hi,

I am very new to ncnn.

can you add  a very simple camera example? with opencv ?

Capture camera(Videocap (0)) detect faces / square and show with cv::im.show

I couldnt find a way to do this due to a newbee..

best

**Comment by cpuimage** [comment]
@MyraBaba check the code of OpenFace(https://github.com/TadasBaltrusaitis/OpenFace),
you will get help.
